### ISSUE TITLE
Unrelated

### ISSUE THREAD

**Issue by jacobEAdamson** [exploser/sam#2]
Hey, just trying to contact you. Not sure what your linked was or anything like that. When you worked on the Rimworld Multiplayer mod, were you able to get it to compile? I've been trying to resolve the rimworld assembly public reference, and wondered if you ran into the same issue when testing your mod

**Comment by vasilevp** [comment]
Hey!
What I did was to decompile Assembly-CSharp.dll from Rimworld and make all methods, fields, etc. `public`.
There are better ways, for example [this gist by Zetrith himself](https://gist.github.com/Zetrith/d86b1d84e993c8117983c09f1a5dcdcd) that should do what you need.

Since I'm not always available, you can ask around on the [Zetrith Discord](https://discord.gg/S4bxXpv) if you have further questions about compiling the mod. Also someone in the [Harmony Discord](https://discord.gg/3TuC4sp) might be of help.

Hope that helps!
